spring:
  application:
    name: studo - prod
  profiles:
    active: prod

  datasource:
    url: jdbc:postgresql://172.10.0.2:5432/db_studo
    username: postgres
    password: 123456

  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate.format_sql: false
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    username:
    password:
    port: 587
    properties:
      mail.smtp.starttls.enable: true

  jackson:
    date-format: yyyy-MM-dd

  cache:
    ehcache:
      config: classpath:ehcache.xml

liquibase:
  enabled: true
  default-schema: studo
  change-log: classpath:db/liquibase-changelog-master.xml

server:
  port: 8443
  context-path: /studo/api
  ssl:
    key-store: classpath:studoKeystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat

studo:
  enviar-email: true
  seguranca:
    enableHttps: false
    origin-permitida: http://localhost
    studo-cliente: studo_cliente
    secret: stud0_cli3nt3_s3cret
    scopes:
      - read
      - write
    authorized-grant-types:
      - password
      - refresh_token
    access-token-validity-seconds: 600
    refresh-token-validity-seconds: 86400
  auditoria:
    user: user
    pass: password
    user-postgres: postgres
    pass-postgres: 123456
    url-data-base: jdbc:postgresql://172.10.0.2:5432/db_studo
    schema: usuarios





